version: "3"

volumes:
  data:
  db:

networks:
  nginx_proxy_frontend:
    # add this if the network is already existing!
    external: true
  nginx_proxy_backend:
    # add this if the network is already existing!
    external: true

services:

  nextcloud-app:
    image: nextcloud:23
    restart: always
    volumes:
      - data:/var/www/html/
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 300s
      retries: 5
      timeout: 10s
    environment:
      - MYSQL_PASSWORD= {change_me}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    networks:
      - nginx_proxy_frontend
      - nginx_proxy_backend

  nextcloud-db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= {change_me}
      - MYSQL_PASSWORD= {change_me}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    healthcheck:
      test: mysql nextcloud --user=root --password= {change_me} --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5 
    networks:
      - nginx_proxy_backend
